server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: auth-server-demo
  security:
    user:
      name: kb@scale.com
      password: uia889nf
    oauth2:
      authorizationserver:
        client:
          frank-client-app:  ## the name of the client app
            registration:
              client-id: "x-pcke-client-x"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:8081/login/oauth2/code/x-pcke-client-x"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
