spring:
  application:
    name: oauth-client-demo

  security:
    oauth2:
      client:
        provider:
          my-github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
#            user-name-attribute: login
        registration:
          complete-github-registration:
            provider: my-github
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
            scope:
              - read:user
            redirect-uri: http://localhost:8081/login/oauth2/code/github
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            client-name: complete github client registration




#        registration:
#          google:
#            client-id: ${google-client-id}
#            client-secret: ${google-client-secret}
#          github:
#            client-id: ${github-client-id}
#            client-secret: ${github-client-secret}


logging:
  level:
    org.springframework.security: TRACE

server:
  port: 8081
